package internal_package_items 

func GetInternalPackageData() []InternalPackageItem {
	return []InternalPackageItem{
        { Name: "@ulld/template", Version: "0.0.0", Path: "/Users/bigsexy/Desktop/current/ulld/apps/template" },
        { Name: "@ulld/website", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/apps/website" },
        { Name: "@ulld/api", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/api" },
        { Name: "@ulld/base-configs", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/baseConfigs" },
        { Name: "@ulld/bib-manager", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/bib-manager" },
        { Name: "@ulld/build", Version: "0.0.125", Path: "/Users/bigsexy/Desktop/current/ulld/packages/build" },
        { Name: "@ulld/build-utils", Version: "0.0.1", Path: "/Users/bigsexy/Desktop/current/ulld/packages/buildUtils" },
        { Name: "@ulld/calendar", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/calendar" },
        { Name: "@ulld/chat", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/chat" },
        { Name: "@ulld/cli", Version: "0.0.2", Path: "/Users/bigsexy/Desktop/current/ulld/packages/cli" },
        { Name: "@ulld/command-palette", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/command-palette" },
        { Name: "@ulld/component-map", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/component-map" },
        { Name: "@ulld/component-configs", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/componentConfigs" },
        { Name: "@ulld/eslint-config", Version: "0.0.118", Path: "/Users/bigsexy/Desktop/current/ulld/packages/config-eslint" },
        { Name: "@ulld/typescript-config", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/config-typescript" },
        { Name: "@ulld/configschema", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/configschema" },
        { Name: "@ulld/cookbook", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/cookbook" },
        { Name: "@ulld/database", Version: "0.0.119", Path: "/Users/bigsexy/Desktop/current/ulld/packages/database" },
        { Name: "@ulld/default-image-map", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/default-image-map" },
        { Name: "@ulld/developer", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/developer" },
        { Name: "@ulld/developer-cli", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/developer-cli" },
        { Name: "@ulld/developer-schemas", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/developer-schemas" },
        { Name: "@ulld/diagram", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/diagram" },
        { Name: "@ulld/editor", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/editor" },
        { Name: "@ulld/embeddable-components", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/embeddable-components" },
        { Name: "@ulld/equations", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/equations" },
        { Name: "@ulld/file-system-utils", Version: "0.0.20", Path: "/Users/bigsexy/Desktop/current/ulld/packages/fileSystemUtilities" },
        { Name: "@ulld/full-form", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/full-form" },
        { Name: "@ulld/health-tracking", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/health-tracking" },
        { Name: "@ulld/hooks", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/hooks" },
        { Name: "@ulld/icons", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/icons" },
        { Name: "@ulld/internal-dev-cli", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/internalDevCli" },
        { Name: "@ulld/jest-presets", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/jest-presets" },
        { Name: "@ulld/journal", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/journal" },
        { Name: "@ulld/kanban", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/kanban" },
        { Name: "@ulld/landing-layouts", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/landing-layouts" },
        { Name: "@ulld/logger", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/logger" },
        { Name: "@ulld/math", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/math" },
        { Name: "@ulld/navigation", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/navigation" },
        { Name: "@ulld/note-network", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/note-network" },
        { Name: "@ulld/notebook", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/notebook" },
        { Name: "@ulld/parsers", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/parsers" },
        { Name: "@ulld/pdf", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/pdf" },
        { Name: "@ulld/plot", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/plot" },
        { Name: "@ulld/render", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/render" },
        { Name: "@ulld/schemas", Version: "0.0.7", Path: "/Users/bigsexy/Desktop/current/ulld/packages/schemas" },
        { Name: "@ulld/snippets", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/snippets" },
        { Name: "@ulld/state", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/state" },
        { Name: "@ulld/tailwind", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/tailwindAndShad" },
        { Name: "@ulld/task-manager", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/task-manager" },
        { Name: "@ulld/test-utils", Version: "0.0.20", Path: "/Users/bigsexy/Desktop/current/ulld/packages/testUtils" },
        { Name: "@ulld/types", Version: "0.0.116", Path: "/Users/bigsexy/Desktop/current/ulld/packages/types" },
        { Name: "@ulld/ui", Version: "0.0.124", Path: "/Users/bigsexy/Desktop/current/ulld/packages/ui" },
        { Name: "@ulld/utilities", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/utilities" },
        { Name: "@ulld/whiteboard", Version: "0.0.126", Path: "/Users/bigsexy/Desktop/current/ulld/packages/whiteboard" },

	}
	}