package internal_package_items 

func GetInternalPackageData() []InternalPackageItem {
	return []InternalPackageItem{
        { Name: "@ulld/template", Version: "0.0.0" },
        { Name: "@ulld/website", Version: "0.0.126" },
        { Name: "@ulld/api", Version: "0.0.126" },
        { Name: "@ulld/base-configs", Version: "0.0.116" },
        { Name: "@ulld/bib-manager", Version: "0.0.126" },
        { Name: "@ulld/build", Version: "0.0.125" },
        { Name: "@ulld/build-utils", Version: "0.0.1" },
        { Name: "@ulld/calendar", Version: "0.0.126" },
        { Name: "@ulld/chat", Version: "0.0.126" },
        { Name: "@ulld/cli", Version: "0.0.2" },
        { Name: "@ulld/command-palette", Version: "0.0.126" },
        { Name: "@ulld/component-map", Version: "0.0.126" },
        { Name: "@ulld/component-configs", Version: "0.0.126" },
        { Name: "@ulld/eslint-config", Version: "0.0.118" },
        { Name: "@ulld/typescript-config", Version: "0.0.116" },
        { Name: "@ulld/configschema", Version: "0.0.126" },
        { Name: "@ulld/cookbook", Version: "0.0.126" },
        { Name: "@ulld/database", Version: "0.0.119" },
        { Name: "@ulld/default-image-map", Version: "0.0.126" },
        { Name: "@ulld/developer", Version: "0.0.126" },
        { Name: "@ulld/developer-cli", Version: "0.0.126" },
        { Name: "@ulld/developer-schemas", Version: "0.0.116" },
        { Name: "@ulld/diagram", Version: "0.0.126" },
        { Name: "@ulld/editor", Version: "0.0.126" },
        { Name: "@ulld/embeddable-components", Version: "0.0.126" },
        { Name: "@ulld/equations", Version: "0.0.126" },
        { Name: "@ulld/file-system-utils", Version: "0.0.20" },
        { Name: "@ulld/full-form", Version: "0.0.126" },
        { Name: "@ulld/health-tracking", Version: "0.0.126" },
        { Name: "@ulld/hooks", Version: "0.0.126" },
        { Name: "@ulld/icons", Version: "0.0.126" },
        { Name: "@ulld/internal-dev-cli", Version: "0.0.116" },
        { Name: "@ulld/jest-presets", Version: "0.0.116" },
        { Name: "@ulld/journal", Version: "0.0.126" },
        { Name: "@ulld/kanban", Version: "0.0.126" },
        { Name: "@ulld/landing-layouts", Version: "0.0.126" },
        { Name: "@ulld/logger", Version: "0.0.116" },
        { Name: "@ulld/math", Version: "0.0.126" },
        { Name: "@ulld/navigation", Version: "0.0.126" },
        { Name: "@ulld/note-network", Version: "0.0.126" },
        { Name: "@ulld/notebook", Version: "0.0.126" },
        { Name: "@ulld/parsers", Version: "0.0.126" },
        { Name: "@ulld/pdf", Version: "0.0.126" },
        { Name: "@ulld/plot", Version: "0.0.126" },
        { Name: "@ulld/render", Version: "0.0.126" },
        { Name: "@ulld/schemas", Version: "0.0.7" },
        { Name: "@ulld/snippets", Version: "0.0.126" },
        { Name: "@ulld/state", Version: "0.0.126" },
        { Name: "@ulld/tailwind", Version: "0.0.116" },
        { Name: "@ulld/task-manager", Version: "0.0.126" },
        { Name: "@ulld/test-utils", Version: "0.0.20" },
        { Name: "@ulld/types", Version: "0.0.116" },
        { Name: "@ulld/ui", Version: "0.0.124" },
        { Name: "@ulld/utilities", Version: "0.0.126" },
        { Name: "@ulld/whiteboard", Version: "0.0.126" },

	}
	}