// Code generated by ULLD dev cli. DO NOT EDIT.

package slot_map

import (
	"fmt"

	"github.com/Uh-little-less-dum/build/pkg/types"
)

type SlotKey string

const (
   Snippets SlotKey = "snippets"
    Math SlotKey = "math"
    Editor SlotKey = "editor"
    UI SlotKey = "UI"
    Bibliography SlotKey = "bibliography"
    TaskManager SlotKey = "taskManager"
    Pdf SlotKey = "pdf"
    Navigation SlotKey = "navigation"
    Dashboard SlotKey = "dashboard"
    Form SlotKey = "form"
    CommandPalette SlotKey = "commandPalette"
    
    NoSlotApplied SlotKey = ""
)


func GetSlots() []Slot {
    return []Slot{
        {
    Id: Snippets,
	SubSlots: []SubSlot{
        NewSubSlot("SnippetListPage"),
        NewSubSlot("AddSnippetPage"),
        NewSubSlot("SnippetList"),
        NewSubSlot("SnippetFilter"),
    }},
        {
    Id: Math,
	SubSlots: []SubSlot{
        NewSubSlot("EquationDetailsModalPage"),
        NewSubSlot("EquationsPage"),
        NewSubSlot("EquationDetailsPage"),
        NewSubSlot("AddEquationPage"),
    }},
        {
    Id: Editor,
	SubSlots: []SubSlot{
        NewSubSlot("EditorModalPage"),
        NewSubSlot("MdxEditorPage"),
        NewSubSlot("LatexEditorPage"),
        NewSubSlot("EditorPage"),
    }},
        {
    Id: UI,
	SubSlots: []SubSlot{
        NewSubSlot("ComponentDocsListPage"),
        NewSubSlot("Pagination"),
        NewSubSlot("logo"),
        NewSubSlot("loadingIndicator"),
        NewSubSlot("confirmationModal"),
        NewSubSlot("ComponentDocumentationPageWrapper"),
        NewSubSlot("AutoSettingsTable"),
        NewSubSlot("AutoSettingFormModal"),
        NewSubSlot("SearchResultsPage"),
        NewSubSlot("BookmarksPage"),
        NewSubSlot("NotesSearchResultsList"),
        NewSubSlot("NoteSummarySearchResult"),
        NewSubSlot("DictionaryLetterList"),
        NewSubSlot("DictionaryPageItem"),
        NewSubSlot("NoteTypeSecondaryFilter"),
        NewSubSlot("NoteTypeSearchResultList"),
        NewSubSlot("MdxNoteContainer"),
    }},
        {
    Id: Bibliography,
	SubSlots: []SubSlot{
        NewSubSlot("BibliographyPage"),
        NewSubSlot("BibEntryDetails"),
    }},
        {
    Id: TaskManager,
	SubSlots: []SubSlot{
        NewSubSlot("TaskManagerPage"),
        NewSubSlot("TaskDetails"),
        NewSubSlot("AddTask"),
        NewSubSlot("AddTaskList"),
        NewSubSlot("TaskListSearchResultList"),
        NewSubSlot("TaskListSearchResult"),
    }},
        {
    Id: Pdf,
	SubSlots: []SubSlot{
        NewSubSlot("FullPdf"),
    }},
        {
    Id: Navigation,
	SubSlots: []SubSlot{
        NewSubSlot("secondary"),
        NewSubSlot("NoteDetailSheet"),
        NewSubSlot("navbar"),
        NewSubSlot("MultiPageSidebar"),
        NewSubSlot("FullScreenNavigationMenu"),
        NewSubSlot("Footer"),
    }},
        {
    Id: Dashboard,
	SubSlots: []SubSlot{
        NewSubSlot("LandingPage"),
    }},
        {
    Id: Form,
	SubSlots: []SubSlot{
        NewSubSlot("SettingsPageContainer"),
    }},
        {
    Id: CommandPalette,
	SubSlots: []SubSlot{
        NewSubSlot("commandPalette"),
    }},
        
        {Id: NoSlotApplied, SubSlots: []SubSlot{}},
    }
}

func SlotIdIterator() []SlotKey {
    return []SlotKey{
        Snippets,
        Math,
        Editor,
        UI,
        Bibliography,
        TaskManager,
        Pdf,
        Navigation,
        Dashboard,
        Form,
        CommandPalette,
        
        NoSlotApplied,
    }
}

func getSlotMapOfDefaultType[T interface{}](defaultVal T) map[string]T {
    var sm = make(map[string]T)
    s := GetSlots()
    for _, k := range s {
        for _, ss := range k.SubSlots {
          sm[fmt.Sprintf("%s/%s", k.Id, ss)] = defaultVal
        }
    }
    return sm
}

// Returns a boolean map in the form of "parentSlot.subSlot = Boolean(slotExists)"
func GetNewSlotBoolMap(defaultVal ...interface{}) map[string]bool {
    return getSlotMapOfDefaultType(false)
}

func GetNewSlotMapCountMap(plugins []types.UlldPlugin) *map[string]int {
    m := getSlotMapOfDefaultType(0)
    for _, p := range plugins {
        for _, c := range p.Components() {
            slotKey := (*c).SlotKey()
            if slotKey != "" {
                m[slotKey] = m[slotKey] + 1
            }
        }
    }
    return &m
}
