// Code generated by MockGen. DO NOT EDIT.
// Source: navigationLink_interface_test.go

// Package build_config_test is a generated GoMock package.
package build_config_test

import (
	gomock "github.com/golang/mock/gomock"
)

// MockNavigationLinkInterface is a mock of NavigationLinkInterface interface.
type MockNavigationLinkInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNavigationLinkInterfaceMockRecorder
}

// MockNavigationLinkInterfaceMockRecorder is the mock recorder for MockNavigationLinkInterface.
type MockNavigationLinkInterfaceMockRecorder struct {
	mock *MockNavigationLinkInterface
}

// NewMockNavigationLinkInterface creates a new mock instance.
func NewMockNavigationLinkInterface(ctrl *gomock.Controller) *MockNavigationLinkInterface {
	mock := &MockNavigationLinkInterface{ctrl: ctrl}
	mock.recorder = &MockNavigationLinkInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNavigationLinkInterface) EXPECT() *MockNavigationLinkInterfaceMockRecorder {
	return m.recorder
}
